import Link from "next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header>
          My app
        </header>
        <header><Link href ="/profile">profile</Link> <Link href ="/">Home</Link> <Link href ="/products">products</Link> <Link href ="/order-product">Order</Link> <Link href ="/settings">settings</Link></header>
        <br />
        {children}
        <br />
        <footer>
          contact us
        </footer>
        </body>
    </html>
  );
}
