import Link from "next/link";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <header  className=" backg">
           <div className="text-5xl text black">
              My app
           </div>        
       <br />
           <div className="display flex justify-around linkin"> 
            <Link href ="/profile"className="">profile</Link> <Link href ="/">Home</Link> <Link href ="/products">products</Link> <Link href ="/order-product">Order</Link> <Link href ="/settings">settings</Link>

           </div>
        </header>
       
              {children}
      
        <footer  className="backg">
          <div className="text-4xl text black"> 
            contact us 
          </div>
        </footer>
        </body>
    </html>
  );
}
